/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5o8Wwynb6Lg
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import ChatBubble from "./chat-bubble";
import Graph from "./graph";
import GraphData from "../../public/graph.json";

export function ChatPage() {
  return (
    <div className="bg-slate-200 p-6 w-full flex h-screen  items-center justify-center gap-2 w-full">
      <div className="w-2/3 h-full rounded-xl overflow-hidden">
        <Graph graphData={GraphData} />
      </div>
      <div className="w-1/3 h-full flex flex-col">
        <div className="flex-grow overflow-y-auto">
          <ChatBubble name="AZ" message="hey" />
        </div>
        <div className="flex gap-2">
          <Input />
          <Button>Search</Button>
        </div>
      </div>
    </div>
  );
}
