/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5o8Wwynb6Lg
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import ChatBubble from "./chat-bubble";

export function ChatBox() {
  return (
    <div className="w-100 h-full flex flex-col gap-2">
      <div className="flex flex-col flex-grow overflow-y-auto place-content-end gap-2">
        <ChatBubble name="AZ --- 1" message="hey" />
        <ChatBubble name="TI --- 2" message="hey" left />
        <ChatBubble name="AZ --- 3" message="hey" />
      </div>
      <div className="flex gap-2">
        <Input />
        <Button>Search</Button>
      </div>
    </div>
  );
}
