/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5o8Wwynb6Lg
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import ChatBubble from "./chat-bubble"

export function ChatPage() {
  return (
    <div className="flex w-full h-screen max-w-3xl border border-gray-200 dark:border-gray-800 rounded-lg overflow-hidden dark:border-gray-800">
      <div className="flex-1 grid flex flex-col">
        <div className="flex-1 flex items-center justify-center p-4">
          <div className="w-full aspect-[1/1] border border-gray-200 border-dashed dark:border-gray-800 rounded-lg flex items-center justify-center dark:border-gray-800">
            <div className="text-center text-gray-400 grid gap-1">
              <ImageIcon className="w-6 h-6 m-auto" />
              <span className="text-sm">Drop an image here or click to upload</span>
            </div>
          </div>
        </div>
      </div>
      <div className="grid w-72 flex flex-col border-l">
        <div className="border-b border-gray-200 dark:border-gray-800 flex items-center p-4">
          <div className="space-y-1">
            <h2 className="text-base font-semibold">Canvas Chat</h2>
            <p className="text-sm leading-none text-gray-500 dark:text-gray-400">You can chat with the canvas here.</p>
          </div>
        </div>
        <div className="flex-1 flex flex-col justify-end p-4">
          <div className="grid gap-4">
            <ChatBubble name="Me" message="Kvo staa manqk?"></ChatBubble>
            <ChatBubble name="AI Bot" message="Biva brat, bachkame"></ChatBubble>
          </div>
        </div>
        <div className="border-t flex items-center p-4">
          <div className="flex-1">
            <Input placeholder="Type a message" />
          </div>
          <Button>Send</Button>
        </div>
      </div>
    </div>
  )
}


function ImageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  )
}
